### ISSUE TITLE
AuthenticationException

### ISSUE THREAD

**Issue by rkumarsriv** [kikovalle/PLGSharepointRestAPI-java#26]
I am trying to do "Get lists of a site"  by using your code sample in README.md
I am getting AuthenticationException at AuthenticationResponseParser.java:40.

Thank you for your help.
-R kumar

**Comment by kikovalle** [comment]
Hello
What kind of sharepoint instance are you trying to access to (OnPremises / Online)?
Are you using valid credentials? I mean, your user and password allows you to navigate the site you are trying to query with de API?
In the README.md the examples show the idea of how to use the API, but not a valid sharepoint site and credentials. You have to test it against your own instance and with your own valid user pass.
If i get more information about what code is throwing the exception maybe i can provide more help

**Comment by rkumarsriv** [comment]
Thanks for the quick response.
The sharepoint is on Azure. The credentials are valid as I am able to access it from browser. Here is the full stacktrace:

Exception in thread "main" com.panxoloto.sharepoint.rest.helper.AuthenticationException: Authentication has failed : Authentication Failure
        at com.panxoloto.sharepoint.rest.helper.AuthenticationResponseParser.parseAuthenticationResponse(AuthenticationResponseParser.java:40)
        at com.panxoloto.sharepoint.rest.helper.AuthTokenHelperOnline.getSecurityTokenUsingUserName(AuthTokenHelperOnline.java:133)
        at com.panxoloto.sharepoint.rest.helper.AuthTokenHelperOnline.receiveSecurityToken(AuthTokenHelperOnline.java:110)
        at com.panxoloto.sharepoint.rest.helper.AuthTokenHelperOnline.init(AuthTokenHelperOnline.java:182)
        at com.panxoloto.sharepoint.rest.PLGSharepointClientOnline.init(PLGSharepointClientOnline.java:75)
        at com.panxoloto.sharepoint.rest.PLGSharepointClientOnline.<init>(PLGSharepointClientOnline.java:47)

**Comment by kikovalle** [comment]
In the exception i see you are using the Online Client instance. If you are not using sharepoint online and you have a On Premises instance installed on azure you should use the OnPremises instance.

**Comment by rkumarsriv** [comment]
PLGSharepointOnPremisesClient constructor parameters is not clear to me. 
Path part is now stored in spSitePrefix . What would spSiteUrl contain ? Could you please give an example for spSiteUrl.

Thanks.
