### ISSUE TITLE
#403 UnauthorizedAccessException

### ISSUE THREAD

**Issue by alex93jansen** [kikovalle/PLGSharepointRestAPI-java#6]
The user account I'm using is the Owner of a group named `veninvTest`, which has a folder named `Invoices`. I'm using the following code to upload a .pdf file to this folder:

```
import org.json.JSONObject;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import com.panxoloto.sharepoint.rest.*;

public class fileUpload {
	public static void main(String args[]) throws Exception {
	String user = "user";
	String passwd = "password";
	String domain = "company.sharepoint.com";
	String spSiteUrl = "/sites/veninvTest";
	
	// Initialize the API
	PLGSharepointClient wrapper = new PLGSharepointClient(user, passwd, domain, spSiteUrl);

	String folder = "sites/veninvTest/Invoices";
    JSONObject jsonMetadata = new JSONObject();
	Resource resource = new ClassPathResource("invoice_637309551232273978.pdf");
    wrapper.uploadFile(folder, resource, jsonMetadata);
	}
}
```

When I run this, I receive the following error:

```
Exception in thread "main" org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [{"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:641)
	at com.panxoloto.sharepoint.rest.PLGSharepointClient.uploadFile(PLGSharepointClient.java:324)
	at util.fileUpload.main(fileUpload.java:23)
```

The user has Full Access permissions for this site and is a Site Collection Administrator. Is there anything I'm doing wrong in my program that could cause this error?

**Comment by kikovalle** [comment]
Sharepoint uses its own permissions and are unique to each library (normally inherited from site). You are experiencing a permission level issue related to user permissions inside the library.
To solve the problem i suggest you to review the user permissions on sharepoint library / folder where you are trying to upload the file. You can check it by uploading a simple file from the browser logged in with the same user account you use to connect from code.

To upload files you need to grant Colaborator permission to the user in the library. Also if the library has unique permissions in folders you have to grant the permission to the user in any folder you want to upload files.

**Comment by alex93jansen** [comment]
The document library I'm attempting to upload a file to, inherits its permissions from its parent (site: veninvTest). The user is part of veninvTest Owners which has Full Access permissions. Uploading a file manually through Sharepoint works fine, it's just the REST API that is showing the 403 Error, hence my question if anything in my program could potentially cause this error.

If I have a site named veninvTest, library named Invoices and a folder named Folder, is it correct the variables would be as follow?

```
String domain = "company.sharepoint.com";
String spSiteUrl = "/sites/veninvTest";
String folder = "/Invoices/folder";
```

**Comment by kikovalle** [comment]
I have to include a better documentation. I'll check how to make this more simple (maybe checking if the folder contains the site uri and if not concat them to ensure the right folder path). 

In the folder you have to include the full folder uri including site and library.
