### ISSUE TITLE
Authentication response does not contain mandatory element

### ISSUE THREAD

**Issue by dengpfei** [kikovalle/PLGSharepointRestAPI-java#63]
What kind of problem is that？
Caused by: com.panxoloto.sharepoint.rest.helper.AuthenticationException: Authentication response does not contain mandatory element {http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd}BinarySecurityToken
	at com.panxoloto.sharepoint.rest.helper.AuthenticationResponseParser.token(AuthenticationResponseParser.java:66)
	at com.panxoloto.sharepoint.rest.helper.AuthenticationResponseParser.parseAuthenticationResponse(AuthenticationResponseParser.java:42)
	at com.panxoloto.sharepoint.rest.helper.AuthTokenHelperOnline.getSecurityTokenUsingUserName(AuthTokenHelperOnline.java:133)
	at com.panxoloto.sharepoint.rest.helper.AuthTokenHelperOnline.receiveSecurityToken(AuthTokenHelperOnline.java:110)
	at com.panxoloto.sharepoint.rest.helper.AuthTokenHelperOnline.init(AuthTokenHelperOnline.java:182)
	at com.panxoloto.sharepoint.rest.PLGSharepointClientOnline.init(PLGSharepointClientOnline.java:77)
	at com.panxoloto.sharepoint.rest.PLGSharepointClientOnline.<init>(PLGSharepointClientOnline.java:49)

**Comment by arcadius** [comment]
Hello @dengpfei 
Any solution for this issue?

**Comment by kikovalle** [comment]
It's not an issue someone can analyze. What you are exposing here is just an stacktrace of an exception that can be thrown for a lot of reasons.

As you can understand i cannot answer on an issue related to an API code, what happens in your code, without knowing what you are trying to do, with what code, kind of sharepoint instance, etc. 

Please dont open issues that are not described in a way that can be analized and are not related to bugs on the API.

I close this issue. If you think there is an API issue there then just give enough information to try to reproduce it.
